server:
  port: 8074

spring:
  application:
    name: "accounts"
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:29092
