server:
  port: 8040

spring:
  application:
    name: "accounts"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:29092
