apiVersion: v1
kind: Service
metadata:
  name: dazee-account-service
  namespace: dazee-banking-app
spec:
  type: NodePort
  selector:
    app: dazee-account-app
  ports:
    - protocol: TCP
      port: 8074
      targetPort: 8074
      nodePort: 30004
